[package]
name = "wgpu_example"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
cfg-if = "1"
pollster = "0.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
bytemuck = { version = "1.18.0", features = ["derive"] }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "22.0", features = ["webgl"] }
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }


[lib]
crate-type = ["cdylib", "rlib"]


# [package]
# name = "tutorial1-window"
# version = "0.1.0"
# authors = ["Ben Hansen <https://github.com/sotrh>"]
# edition = "2018"

# [lib]
# crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "tutorial1-window"
# path = "src/main.rs"

# [dependencies]
# cfg-if = "1"
# winit = { version = "0.29", features = ["rwh_05"] }
# env_logger = "0.10"
# log = "0.4"
# wgpu = { version = "22.0", features = ["webgl"] }
# pollster = "0.3"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# console_error_panic_hook = "0.1.6"
# console_log = "1.0"
# wgpu = { version = "22.0", features = ["webgl"]}
# wasm-bindgen = "0.2"
# wasm-bindgen-futures = "0.4.30"
# web-sys = { version = "0.3.69", features = [
#     "Document",
#     "Window",
#     "Element",
# ]}
